# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XFYHSzBk18gMr0qnQM4UlZvy1mtuYDVq
"""

import streamlit as st
from dotenv import load_dotenv

from langchain_community.document_loaders import UnstructuredHTMLLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_chroma import Chroma
from langchain_openai import OpenAIEmbeddings, ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain.chains import RetrievalQA

# ------------------------------
# Load Environment Variables
# ------------------------------
load_dotenv()

# ------------------------------
# Page Configuration
# ------------------------------
st.set_page_config(
    page_title="Samsung AI Manual Assistant",
    page_icon="🤖",
    layout="wide"
)

# ------------------------------
# CSS
# ------------------------------
st.markdown("""
<style>

.stApp{
background:linear-gradient(to right,#edf6ff,#ffffff);
}

.main-title{
text-align:center;
font-size:40px;
font-weight:bold;
color:#0B5ED7;
margin-bottom:5px;
}

.sub-title{
text-align:center;
font-size:18px;
color:gray;
margin-bottom:25px;
}

[data-testid="stSidebar"]{
background:#0B5ED7;
}

[data-testid="stSidebar"] *{
color:white;
}

.stChatMessage{
padding:15px;
border-radius:15px;
margin-bottom:12px;
box-shadow:0px 4px 10px rgba(0,0,0,0.1);
}

.footer{
text-align:center;
color:gray;
margin-top:40px;
}

</style>
""", unsafe_allow_html=True)

# ------------------------------
# Header
# ------------------------------

st.markdown(
"""
<div class="main-title">
🤖 Samsung Washing Machine AI Assistant
</div>

<div class="sub-title">
Ask anything about your Samsung Washing Machine Manual using AI.
</div>
""",
unsafe_allow_html=True,
)

# ------------------------------
# Sidebar
# ------------------------------

st.sidebar.title("📘 Manual Assistant")

st.sidebar.write("### Features")

st.sidebar.success("✔ AI Powered")

st.sidebar.success("✔ Manual Search")

st.sidebar.success("✔ LangChain")

st.sidebar.success("✔ OpenAI")

st.sidebar.success("✔ ChromaDB")

st.sidebar.markdown("---")

st.sidebar.info(
"""
Upload your Samsung Manual (HTML) and ask questions.

Examples:

• How do I clean the filter?

• What does Error 5C mean?

• Child Lock?

• Eco Bubble?
"""
)

# ------------------------------
# Load Documents
# ------------------------------

@st.cache_resource
def create_chain():

    loader = UnstructuredHTMLLoader("How to use the various modes of the washing machine _ Samsung LEVANT.html")

    docs = loader.load()

    splitter = RecursiveCharacterTextSplitter(
        chunk_size=1000,
        chunk_overlap=200
    )

    documents = splitter.split_documents(docs)

    embeddings = OpenAIEmbeddings()

    vectorstore = Chroma.from_documents(
        documents,
        embeddings
    )

    retriever = vectorstore.as_retriever()

    llm = ChatOpenAI(
        model="gpt-4o-mini",
        temperature=0
    )

    prompt = ChatPromptTemplate.from_template("""
You are a helpful Samsung Washing Machine assistant.

Answer ONLY using the given context.

If the answer is not present, say:

"I couldn't find that information in the manual."

Context:
{context}

Question:
{question}

Answer:
""")

    qa = RetrievalQA.from_chain_type(
        llm=llm,
        retriever=retriever,
        chain_type="stuff",
        chain_type_kwargs={
            "prompt": prompt
        }
    )

    return qa


qa_chain = create_chain()

# ------------------------------
# Chat History
# ------------------------------

if "messages" not in st.session_state:
    st.session_state.messages=[]

for message in st.session_state.messages:

    with st.chat_message(message["role"]):
        st.markdown(message["content"])

# ------------------------------
# User Input
# ------------------------------

question = st.chat_input("Ask your question...")

if question:

    st.session_state.messages.append(
        {
            "role":"user",
            "content":question
        }
    )

    with st.chat_message("user"):
        st.markdown(question)

    with st.chat_message("assistant"):

        with st.spinner("Searching Manual..."):

            response = qa_chain.invoke(question)

            answer = response["result"]

            st.markdown(answer)

    st.session_state.messages.append(
        {
            "role":"assistant",
            "content":answer
        }
    )

# ------------------------------
# Footer
# ------------------------------

st.markdown(
"""
<div class="footer">
Made with ❤️ using Streamlit • LangChain • ChromaDB • OpenAI
</div>
""",
unsafe_allow_html=True,
)
